#!/bin/bash
#updated 4/19/24 for qrcp github releases page change
platform=$(uname -o)
platform=${platform,,}
platform=$(echo ${platform}/${platform} | awk -F/ '{print $2}')

arch=$(uname -m)
if [ $arch == 'armv7l' ]; then
   arch=armv7
fi
if [ $arch == 'x86_64' ]; then
    arch='amd64'
fi
if [ $arch == 'aarch64' ]; then
    arch='arm64'
fi

installed_qrcp=$(dpkg --list  qrcp 2>/dev/null| tail -n1 | awk '{print $3}')


ver=$(curl -sL https://github.com/claudiodangelis/qrcp/releases | grep -i -m1 "/claudiodangelis/qrcp/releases/tag/" | awk -F/ {'print $6'} | sed -e 's/href="\(.*\)"/\1/' | awk -F\" {'print $1'}| awk -F\" '{print $1}')
# check to see if we have the latest
if [ "$ver." != "$installed_qrcp." ]; then
    # get the latest release for this hardware architecture, from the list of releases
    fn=$(curl -sL curl -sL https://github.com/claudiodangelis/qrcp/releases/expanded_assets/$ver | grep -m1 "${platform}_${arch}" | awk -F'"'  '{print $2}')
    if [ '$fn'. != '.' ]; then
        # download the  file for this machine
        curl -sL https://github.com$fn > xx.deb
        # install qrcp
        sudo dpkg -i xx.deb >/dev/null
    else
        echo 'unable to find qrpc module for $arch'
    fi
fi
# add the image orientation tool
sudo apt-get -y install exiftran >/dev/null
# watch out for multiple networks, just write the config file
nets=$(ip link show | grep mtu | grep -v lo | grep up | grep -v -i docker | grep "state UP" | awk -F: '{print $2}' | awk '{print $1}')
# if only one network
if [ $(echo $nets | wc -w ) -eq 1 ]; then
   # write it out to conf file
   echo "{ \"interface\": \"$nets\" }" >qrcp.json
else
    # split names into an array
    adapters=($nets) # split to array $diffs

    # if there are different files (array size greater than zero)
    if [ ${#adapters[@]} -gt 0 ]; then
        for adapter in "${adapters[@]}"
        do
	         # check to see if this is a wireless network (mirror on the wall)
             f=$(iwconfig $adapter | grep ESSID | awk '{print $1}')
             if [ "$f". != '.' ]; then
		        # use this adapter
                echo "{ \"interface\": \"$f\" }" >qrcp.json
		        # done with list
                break;
             fi
        done
    fi
fi
rm ../../app/locales/??c.json >/dev/null 2>&1
